### ISSUE TITLE
Single touch in mobile causes double click on button prev/next

### ISSUE THREAD

**Issue by JAFB321** [nikitanickzhukov/jquery-inputarrow#1]
**In mobile Screen:**
- When you do a single touch on the prev/next button it fire the count event 2 times.. So, the number increase or decrement the double of the "step" value..

I think found the problem, and it's on these following lines:

```
this.$prev.on('mousedown touchstart', () => {    // <----- ** Remove "touchstart" ** 
                this.startCounting(-1);
            }).on('mouseup mouseout touchend', () => {
                if (this.__isStarted) {
                    if (this.__isCounting) {
                        this.stopCounting();
                    } else {
                        this.__clearCounting();
                        this.count(-1);
                    }
                }
            });

            this.$next.on('mousedown touchstart', () => {   // <----- ** Remove "touchstart" ** 
                this.startCounting(1);
            }).on('mouseup mouseout touchend', () => {
                if (this.__isStarted) {
                    if (this.__isCounting) {
                        this.stopCounting();
                    } else {
                        this.__clearCounting();
                        this.count(1);
                    }
                }
            });

```
Maybe it isn't the most clean solution, but it works for me 👍🏻

**Comment by nikitanickzhukov** [comment]
Hi Jose Antonio!
The problem really occurred on mobile devices in cases of single-touch increment.
Unfortunately, your solution caused problems when we use long push on mobile devices.

I fixed this bug by separating touch and mouse events and using related events for each type of device: https://github.com/nikitanickzhukov/jquery-inputarrow/commit/cf3c0329253a7a10daa283df21e87a8fd390dd59

Thanks for your bug report!
Please close this issue when you make sure that the bug is fixed.

**Comment by JAFB321** [comment]
Perfect Nikita!!! thank for you too!
I will close the issue.. excellent work in your repo!
